src/Roombait/Controllers/ResidenceController.cs
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNet.Authorization;
using Microsoft.AspNet.Diagnostics;
using Microsoft.AspNet.Http.Features;
using Microsoft.AspNet.Mvc;
using Microsoft.Data.Entity;
using Roombait.Models;

namespace Roombait.Controllers
{
    public class ResidenceController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ResidenceController(ApplicationDbContext context)
        {
            _context = context;
        }

        [Authorize]
        public IActionResult Index()
        {
            List<Residence> result = null;

            if (User.HasClaim("Admin", "true"))
            {
                result = _context.Residences
                    .Include(d=>d.Residents).ToList();
            }
            else
            {
                result = _context.Residences
                        .Where(residence => residence.Residents.Any(user => user.Id == User.GetUserId()))
                        .Include(d => d.Residents)
                        .ToList();
            }

            return View(new ViewModels.Residence.ResidenceIndexViewModel
            {
                Residences = result
            });
        }

        [Authorize]
        public async Task<IActionResult> View(int id)
        {
            var result = await _context.Residences
                .Include(d=>d.Owner)
                .Include(d=>d.Residents)
                .Include(d=>d.Activites)
                .ThenInclude(d=>d.Performances)
                .SingleOrDefaultAsync(d => d.ResidenceID == id);

            return View(result);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Residence residence)
        {
            if (!ModelState.IsValid)
            {
                return HttpBadRequest();
            }

            var currentUser = _context.Users.First(d => d.Id == User.GetUserId());

            residence.Owner = currentUser;
            residence.Residents.Add(currentUser);

            _context.Residences.Add(residence);
            _context.SaveChanges();

            return new HttpOkResult();
        }

    }
}

src/Roombait/Views/Shared/_Layout.cshtml
@using System.Security.Claims
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>@ViewData["Title"] - Roombait</title>

        <environment names="Development">
            <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css"/>
            <link rel="stylesheet" href="~/lib/toastr/toastr.css"/>
            <link rel="stylesheet" href="~/css/site.css" />
        </environment>
        <environment names="Staging,Production">
            <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.5/css/bootstrap.min.css"
                  asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
                  asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"/>
            <link rel="stylesheet" href="~/lib/toastr/toastr.min.css" />
            <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true"/>
        </environment>

        @RenderSection("styles", required: false)
    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a asp-controller="Home" asp-action="Index" class="navbar-brand">Roombait</a>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <!--<li><a asp-controller="Home" asp-action="Index">Home</a></li>-->
                        @if (Context.User.IsSignedIn())
                        {
                            <li><a asp-controller="Residence" asp-action="Index">Residences</a></li>
                        }
                        <!--
                            <li><a asp-controller="Home" asp-action="About">About</a></li>
                            <li><a asp-controller="Home" asp-action="Contact">Contact</a></li>
                        -->
                    </ul>
                    @await Html.PartialAsync("_LoginPartial")
                </div>
            </div>
        </div>
        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - Roombait</p>
            </footer>
        </div>

        <environment names="Development">
            <script src="~/lib/jquery/dist/jquery.js"></script>
            <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
            <script src="~/js/site.js" asp-append-version="true"></script>
            <script src="~/lib/toastr/toastr.js"></script>
        </environment>
        <environment names="Staging,Production">
            <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.1.4.min.js"
                    asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                    asp-fallback-test="window.jQuery">
            </script>
            <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.5/bootstrap.min.js"
                    asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                    asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
            </script>
            <script src="~/js/site.min.js" asp-append-version="true"></script>
            <script src="~/lib/toastr/toastr.min.js"></script>
        </environment>

        @RenderSection("scripts", required: false)
    </body>
</html>